# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1423, 882)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 0, 1371, 801))
        self.stackedWidget.setObjectName("stackedWidget")
        self.Intro_page = QtWidgets.QWidget()
        self.Intro_page.setObjectName("Intro_page")
        self.IntroGroupBox = QtWidgets.QGroupBox(self.Intro_page)
        self.IntroGroupBox.setGeometry(QtCore.QRect(440, 190, 421, 411))
        self.IntroGroupBox.setTitle("")
        self.IntroGroupBox.setObjectName("IntroGroupBox")
        self.BrowseButton = QtWidgets.QPushButton(self.IntroGroupBox)
        self.BrowseButton.setGeometry(QtCore.QRect(320, 110, 93, 28))
        self.BrowseButton.setObjectName("BrowseButton")
        self.FileNameTextEdit = QtWidgets.QLineEdit(self.IntroGroupBox)
        self.FileNameTextEdit.setGeometry(QtCore.QRect(40, 110, 271, 21))
        self.FileNameTextEdit.setObjectName("FileNameTextEdit")
        self.ProcessButton = QtWidgets.QPushButton(self.IntroGroupBox)
        self.ProcessButton.setGeometry(QtCore.QRect(120, 160, 141, 71))
        self.ProcessButton.setObjectName("ProcessButton")
        self.ErrorLabel = QtWidgets.QLabel(self.IntroGroupBox)
        self.ErrorLabel.setGeometry(QtCore.QRect(44, 240, 361, 20))
        self.ErrorLabel.setText("")
        self.ErrorLabel.setObjectName("ErrorLabel")
        self.stackedWidget.addWidget(self.Intro_page)
        self.Graph_page = QtWidgets.QWidget()
        self.Graph_page.setObjectName("Graph_page")
        self.KeyGroupBox = QtWidgets.QGroupBox(self.Graph_page)
        self.KeyGroupBox.setGeometry(QtCore.QRect(930, 130, 431, 191))
        self.KeyGroupBox.setObjectName("KeyGroupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.KeyGroupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(129, 19, 291, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.CumleScoreLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.CumleScoreLabel.setObjectName("CumleScoreLabel")
        self.gridLayout.addWidget(self.CumleScoreLabel, 4, 0, 1, 1)
        self.ThresholdLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ThresholdLabel.setObjectName("ThresholdLabel")
        self.gridLayout.addWidget(self.ThresholdLabel, 3, 0, 1, 1)
        self.AnlamsalLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.AnlamsalLabel.setObjectName("AnlamsalLabel")
        self.gridLayout.addWidget(self.AnlamsalLabel, 0, 0, 1, 1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.KeyGroupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 101, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(10, 20, 10, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.greenLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.greenLabel.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.greenLabel.setText("")
        self.greenLabel.setObjectName("greenLabel")
        self.verticalLayout.addWidget(self.greenLabel)
        self.yellowLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.yellowLabel.setAutoFillBackground(False)
        self.yellowLabel.setStyleSheet("background-color:rgb(255, 255, 127)")
        self.yellowLabel.setText("")
        self.yellowLabel.setObjectName("yellowLabel")
        self.verticalLayout.addWidget(self.yellowLabel)
        self.pinkLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.pinkLabel.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.pinkLabel.setText("")
        self.pinkLabel.setObjectName("pinkLabel")
        self.verticalLayout.addWidget(self.pinkLabel)
        self.groupBox_5 = QtWidgets.QGroupBox(self.Graph_page)
        self.groupBox_5.setGeometry(QtCore.QRect(930, 440, 431, 181))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_5)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(130, 20, 374, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 107, 151))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_2.setContentsMargins(10, 20, 10, 20)
        self.verticalLayout_2.setSpacing(50)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.BenzerlikThresholdTextEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.BenzerlikThresholdTextEdit.setObjectName("BenzerlikThresholdTextEdit")
        self.verticalLayout_2.addWidget(self.BenzerlikThresholdTextEdit)
        self.BenzerlikThresholdTextEdit_2 = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.BenzerlikThresholdTextEdit_2.setObjectName("BenzerlikThresholdTextEdit_2")
        self.verticalLayout_2.addWidget(self.BenzerlikThresholdTextEdit_2)
        self.ReloadButton = QtWidgets.QPushButton(self.Graph_page)
        self.ReloadButton.setGeometry(QtCore.QRect(930, 630, 131, 81))
        self.ReloadButton.setObjectName("ReloadButton")
        self.optionsErrorLabel = QtWidgets.QLabel(self.Graph_page)
        self.optionsErrorLabel.setGeometry(QtCore.QRect(1070, 630, 251, 51))
        self.optionsErrorLabel.setText("")
        self.optionsErrorLabel.setObjectName("optionsErrorLabel")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Graph_page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 921, 771))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.GraphLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.GraphLayout.setContentsMargins(0, 0, 0, 0)
        self.GraphLayout.setObjectName("GraphLayout")
        self.groupBox = QtWidgets.QGroupBox(self.Graph_page)
        self.groupBox.setGeometry(QtCore.QRect(930, 320, 431, 121))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 401, 92))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.GloveModel_Radio = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.GloveModel_Radio.setMinimumSize(QtCore.QSize(0, 50))
        self.GloveModel_Radio.setStyleSheet("QRadioButton::indicator {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QRadioButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-color: rgb(81, 81, 81);\n"
"    border-style: solid;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::checked{\n"
"    \n"
"    background-color: rgb(194, 194, 194);\n"
"}\n"
"\n"
"\n"
"")
        self.GloveModel_Radio.setObjectName("GloveModel_Radio")
        self.horizontalLayout.addWidget(self.GloveModel_Radio)
        self.BertModel_Radio = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.BertModel_Radio.setMinimumSize(QtCore.QSize(0, 50))
        self.BertModel_Radio.setStyleSheet("QRadioButton::indicator {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QRadioButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-color: rgb(81, 81, 81);\n"
"    border-style: solid;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::checked{\n"
"    \n"
"    background-color: rgb(194, 194, 194);\n"
"}\n"
"\n"
"\n"
"")
        self.BertModel_Radio.setObjectName("BertModel_Radio")
        self.horizontalLayout.addWidget(self.BertModel_Radio)
        self.stackedWidget.addWidget(self.Graph_page)
        self.Summary_page = QtWidgets.QWidget()
        self.Summary_page.setObjectName("Summary_page")
        self.RougeScoreTextLabel = QtWidgets.QLabel(self.Summary_page)
        self.RougeScoreTextLabel.setGeometry(QtCore.QRect(1050, 270, 91, 61))
        self.RougeScoreTextLabel.setObjectName("RougeScoreTextLabel")
        self.RogueScoreLabel = QtWidgets.QLabel(self.Summary_page)
        self.RogueScoreLabel.setGeometry(QtCore.QRect(1140, 270, 91, 61))
        self.RogueScoreLabel.setObjectName("RogueScoreLabel")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.Summary_page)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 20, 931, 761))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.manualSummary_summary = QtWidgets.QTextBrowser(self.verticalLayoutWidget_5)
        self.manualSummary_summary.setObjectName("manualSummary_summary")
        self.verticalLayout_5.addWidget(self.manualSummary_summary)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.processedSummary_summary = QtWidgets.QTextBrowser(self.verticalLayoutWidget_5)
        self.processedSummary_summary.setObjectName("processedSummary_summary")
        self.verticalLayout_5.addWidget(self.processedSummary_summary)
        self.stackedWidget.addWidget(self.Summary_page)
        self.OriginalText_page = QtWidgets.QWidget()
        self.OriginalText_page.setObjectName("OriginalText_page")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.OriginalText_page)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 50, 931, 731))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.mainText_original = QtWidgets.QTextBrowser(self.verticalLayoutWidget_4)
        self.mainText_original.setObjectName("mainText_original")
        self.verticalLayout_4.addWidget(self.mainText_original)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.manualSummary_original = QtWidgets.QTextBrowser(self.verticalLayoutWidget_4)
        self.manualSummary_original.setObjectName("manualSummary_original")
        self.verticalLayout_4.addWidget(self.manualSummary_original)
        self.title_label = QtWidgets.QLabel(self.OriginalText_page)
        self.title_label.setGeometry(QtCore.QRect(10, 20, 311, 21))
        self.title_label.setText("")
        self.title_label.setObjectName("title_label")
        self.stackedWidget.addWidget(self.OriginalText_page)
        self.NagivationGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.NagivationGroupBox.setGeometry(QtCore.QRect(950, 10, 431, 111))
        self.NagivationGroupBox.setObjectName("NagivationGroupBox")
        self.OriginalNav_Radio = QtWidgets.QRadioButton(self.NagivationGroupBox)
        self.OriginalNav_Radio.setGeometry(QtCore.QRect(10, 20, 131, 81))
        self.OriginalNav_Radio.setStyleSheet("QRadioButton::indicator {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QRadioButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-color: rgb(81, 81, 81);\n"
"    border-style: solid;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::checked{\n"
"    \n"
"    background-color: rgb(194, 194, 194);\n"
"}\n"
"\n"
"\n"
"")
        self.OriginalNav_Radio.setObjectName("OriginalNav_Radio")
        self.GraphNav_Radio = QtWidgets.QRadioButton(self.NagivationGroupBox)
        self.GraphNav_Radio.setGeometry(QtCore.QRect(150, 20, 131, 81))
        self.GraphNav_Radio.setStyleSheet("QRadioButton::indicator {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QRadioButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-color: rgb(81, 81, 81);\n"
"    border-style: solid;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::checked{\n"
"    \n"
"    background-color: rgb(194, 194, 194);\n"
"}\n"
"\n"
"")
        self.GraphNav_Radio.setObjectName("GraphNav_Radio")
        self.SummaryNav_Radio = QtWidgets.QRadioButton(self.NagivationGroupBox)
        self.SummaryNav_Radio.setGeometry(QtCore.QRect(290, 20, 131, 81))
        self.SummaryNav_Radio.setStyleSheet("QRadioButton::indicator {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QRadioButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-color: rgb(81, 81, 81);\n"
"    border-style: solid;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::checked{\n"
"    \n"
"    background-color: rgb(194, 194, 194);\n"
"}\n"
"\n"
"")
        self.SummaryNav_Radio.setObjectName("SummaryNav_Radio")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1423, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BrowseButton.setText(_translate("MainWindow", "Browse"))
        self.ProcessButton.setText(_translate("MainWindow", "Process"))
        self.KeyGroupBox.setTitle(_translate("MainWindow", "Key"))
        self.CumleScoreLabel.setText(_translate("MainWindow", "cumle skoru"))
        self.ThresholdLabel.setText(_translate("MainWindow", "Benzerlik thresholdu"))
        self.AnlamsalLabel.setText(_translate("MainWindow", "Anlamsal Benzerlik"))
        self.groupBox_5.setTitle(_translate("MainWindow", "options"))
        self.label_8.setText(_translate("MainWindow", "cumle skoru thresholdu "))
        self.label_9.setText(_translate("MainWindow", "Benzerlik thresholdu"))
        self.BenzerlikThresholdTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.BenzerlikThresholdTextEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.ReloadButton.setText(_translate("MainWindow", "Relaod"))
        self.groupBox.setTitle(_translate("MainWindow", "Model"))
        self.GloveModel_Radio.setText(_translate("MainWindow", "glove"))
        self.BertModel_Radio.setText(_translate("MainWindow", "bert"))
        self.RougeScoreTextLabel.setText(_translate("MainWindow", "ROUGE score:"))
        self.RogueScoreLabel.setText(_translate("MainWindow", "[ROUGE score]"))
        self.label_3.setText(_translate("MainWindow", "manual summary"))
        self.label_4.setText(_translate("MainWindow", "nltk summary"))
        self.processedSummary_summary.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "input text"))
        self.label.setText(_translate("MainWindow", "manual summary"))
        self.manualSummary_original.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.NagivationGroupBox.setTitle(_translate("MainWindow", "Navigation"))
        self.OriginalNav_Radio.setText(_translate("MainWindow", "Original Text"))
        self.GraphNav_Radio.setText(_translate("MainWindow", "Graph"))
        self.SummaryNav_Radio.setText(_translate("MainWindow", "Summary"))
